pipeline {
  agent {
    label 'rclone'
  }

  environment {
    RCLONE_CONFIG = credentials('rclone')
  }

  stages {
    stage('media-wasabi-b2') {
      steps {
        sh 'rclone sync -v media-wasabi: media-b2:'
      }
    }
  }
}
