resources:
  - name: cassiecluster
    icon: github
    type: git
    source:
      uri: https://github.com/SapphicCode/cassiecluster.git
      branch: mistress

jobs:
  - name: ansible-play
    serial: yes
    plan:
      - get: cassiecluster
        trigger: yes
      - task: decrypt
        file: cassiecluster/ci/concourse/decrypt.yml
      - task: ansible
        file: cassiecluster/ci/concourse/ansible.yml

  - name: pipeline
    serial: yes
    plan:
      - get: cassiecluster
        trigger: yes
      - set_pipeline: self
        file: cassiecluster/ci/concourse/pipeline.yml
