pipeline {
  agent {
    // https://www.jenkins.io/doc/book/pipeline/syntax/#agent-parameters
    dockerfile {
      dir 'jobs/jenkins/ansible'
    }
  }

  environment {
    VAULT_ADDR = credentials('vault_address')
    VAULT_APPROLE = credentials('4bc81c9f-c9fa-474c-be80-9ede2ec35faf')

    ANSIBLE_CONFIG = './configs/ansible/ansible.cfg'
  }

  stages {
    stage('Prepare build environment') {
      steps {
        checkout scm

        sh 'vault write -field=token auth/approle/login role_id=${VAULT_APPROLE_USR} secret_id=${VAULT_APPROLE_PSW} | vault login token=- > /dev/null'
        sh 'ci/decrypt.sh'
        sh 'chmod u=rw,go= configs/openssh/id_ed25519'
      }
    }
    stage('Run playbooks') {
      steps {
        sh 'ansible-playbook -i configs/ansible/inventory playbooks/00-users.yml'
      }
    }
  }
}
