pipeline {
  agent {
    // https://www.jenkins.io/doc/book/pipeline/syntax/#agent-parameters
    dockerfile {
      dir 'jobs/jenkins/ansible'
    }
  }
  stages {
    stage('Prepare build environment') {
      steps {
        checkout scm
        sh 'ci/decrypt.sh'
      }
    }
  }
}
